### ISSUE TITLE
TwilioException: Media upload error 0:-12 Cannot upload one or more media files

### ISSUE THREAD

**Issue by ajitdubey-mob-ibtech** [twilio/twilio-conversations-demo-android-kotlin#46]
If the network is disconnected in between uploading the media file, we found an exception. Can you please help me to fix this issue?

**Twilio SDK version** = 4.0.1
**Android SDK**= 13

**Exception:**
com.twilio.util.TwilioException: Media upload error 0:-12 Cannot upload one or more media files.

**Comment by berkus** [comment]
Catch it, and retry once network is back.

**Comment by rusmonster** [comment]
Hello @ajitdubey-mob-ibtech!
This is expected behaviour. Currently SDK doesn't retry to upload media if first attempt has failed.
Moreover even for non-media messages the `sendMessage()` method will throw exception if SDK cannot send the message until [CommandTimeout](https://sdk.twilio.com/android/conversations/releases/4.0.2/docs/-conversations%20-android%20-s-d-k/com.twilio.conversations/-conversations-client/-properties/-builder/set-command-timeout.html)

Correct approach here is to catch the exception then handle it according to your app requirements, for instance:
- show and "retry" button in UI
- listen to [ConversationClientListener.onConnectionStateChanged](https://sdk.twilio.com/android/conversations/releases/4.0.2/docs/-conversations%20-android%20-s-d-k/com.twilio.conversations/-conversations-client-listener/on-connection-state-change.html) event and retry message sending when `ConnectionState` switched to [CONNECTED](https://sdk.twilio.com/android/conversations/releases/4.0.2/docs/-conversations%20-android%20-s-d-k/com.twilio.conversations/-conversations-client/-connection-state/index.html)

**Comment by ajitdubey-mob-ibtech** [comment]
Thanks, @berkus, and @rusmonster for your quick response.
I am showing the retry button in case of failure or error messages but didn't catch the exception. 
Now I can catch the exception and handle it accordingly.
